version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
