# NodeJS Version 20
FROM node:20.11.0-bookworm-slim

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN npm install --legacy-peer-deps

# Set Env
ENV NODE_ENV production

EXPOSE 4000

RUN npm run build

# Cmd script
CMD ["npm", "run", "serve:ssr:PRLiveTFT-frontend"]
